"""
Build reference/accounts.json from the pilot workbook's Account tab -- the
canonical account list that OCR-garbled labels are fuzzy-matched against.

    python reference/build_accounts.py path/to/CJS_Title_III_Science_Pilot_Schema_Loaded_v8.xlsx

Only canonical_name is matched; historical_names stays reserved for genuine
renames and is carried along untouched.
"""

import hashlib
import json
import sys
from pathlib import Path

import openpyxl

FIELDS = ("canonical_account_id", "canonical_name", "agency", "bureau", "status",
          "historical_names", "fund_type", "subcommittee")


def build(workbook):
    wb = openpyxl.load_workbook(workbook, data_only=True, read_only=True)
    rows = list(wb["Account"].iter_rows(values_only=True))
    head = rows[0]
    accounts = [{k: v for k, v in zip(head, r) if k in FIELDS} for r in rows[1:] if r[0]]
    out = {"source": f"{Path(workbook).name} (sha256 {hashlib.sha256(Path(workbook).read_bytes()).hexdigest()[:16]}), "
                     f"Account tab; generated by {Path(__file__).name} -- do not edit by hand.",
           "accounts": accounts}
    dest = Path(__file__).resolve().parent / "accounts.json"
    dest.write_text(json.dumps(out, indent=2) + "\n")
    print(f"{dest}: {len(accounts)} accounts")


if __name__ == "__main__":
    build(sys.argv[1])
