"""
Build reference/accounts.json from the pilot workbook -- the canonical account
list that OCR-garbled labels are fuzzy-matched against (accounts.py).

    python reference/build_accounts.py reference/CJS_Title_III_Science_Pilot_Schema_Loaded_v16.xlsx

Matched names per account: canonical_name (Account tab) plus its former names
from the Historical Name tab, one row per name. Only rows with human_reviewed
TRUE are matched against. Account.historical_names is the denormalized,
';'-separated display list of the same names; it is checked against the tab
here (the build stops if they disagree) but never parsed for matching, so the
separator can't affect matching. Account.notes is carried along as "notes".
"""

import hashlib
import json
import sys
from pathlib import Path

import openpyxl

FIELDS = ("canonical_account_id", "canonical_name", "agency", "bureau", "status",
          "fund_type", "subcommittee", "notes")


def truthy(v):
    return v is True or str(v).strip().upper() == "TRUE"


def rows_of(wb, sheet):
    rows = list(wb[sheet].iter_rows(values_only=True))
    return [dict(zip(rows[0], r)) for r in rows[1:] if any(v is not None for v in r)]


def accounts_from_workbook(workbook):
    """-> the accounts.json document for this workbook (nothing written)."""
    wb = openpyxl.load_workbook(workbook, data_only=True, read_only=True)
    account_rows = [r for r in rows_of(wb, "Account") if r.get("canonical_account_id")]
    former = rows_of(wb, "Historical Name")
    ids = {r["canonical_account_id"] for r in account_rows}

    unknown = sorted({h["canonical_account_id"] for h in former} - ids)
    if unknown:
        raise SystemExit(f"Historical Name rows point at accounts not in the Account tab: {unknown}")
    problems = []
    for r in account_rows:
        display = [n.strip() for n in (r.get("historical_names") or "").split(";") if n.strip()]
        tab = [h["former_name"] for h in former if h["canonical_account_id"] == r["canonical_account_id"]]
        if display != tab:
            problems.append(f"{r['canonical_account_id']}: Account.historical_names {display} != Historical Name tab {tab}")
    if problems:
        raise SystemExit("Account.historical_names and the Historical Name tab disagree:\n  " + "\n  ".join(problems))

    accounts = []
    for r in account_rows:
        a = {k: r.get(k) for k in FIELDS}
        mine = [h for h in former if h["canonical_account_id"] == r["canonical_account_id"]]
        a["historical_names"] = [h["former_name"] for h in mine if truthy(h.get("human_reviewed"))]
        a["historical_name_ids"] = [h["historical_name_id"] for h in mine if truthy(h.get("human_reviewed"))]
        a["historical_names_unreviewed"] = [h["former_name"] for h in mine if not truthy(h.get("human_reviewed"))]
        accounts.append(a)

    digest = hashlib.sha256(Path(workbook).read_bytes()).hexdigest()
    return {"source": f"{Path(workbook).name} (sha256 {digest[:16]}), Account and Historical Name tabs; "
                      f"generated by {Path(__file__).name} -- do not edit by hand.",
            "accounts": accounts}


def build(workbook):
    out = accounts_from_workbook(workbook)
    accounts = out["accounts"]
    dest = Path(__file__).resolve().parent / "accounts.json"
    dest.write_text(json.dumps(out, indent=2) + "\n")
    print(f"{dest}: {len(accounts)} accounts, "
          f"{sum(len(a['historical_names']) for a in accounts)} reviewed former names")


if __name__ == "__main__":
    build(sys.argv[1])
